// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl8wCN2pEttwqUjnNl1qJ_uMwsNc77bDQ',
    appId: '1:639171720797:android:6c5b28c5a999db9c107fb4',
    messagingSenderId: '639171720797',
    projectId: 'adhd-journal-flutter',
    storageBucket: 'adhd-journal-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdP5LCqg9cDIIiY46A2Z2t9j2_OTtD2qQ',
    appId: '1:639171720797:ios:75122e294e519e47107fb4',
    messagingSenderId: '639171720797',
    projectId: 'adhd-journal-flutter',
    storageBucket: 'adhd-journal-flutter.appspot.com',
    androidClientId:
        '639171720797-1t83e6st47g8q6gui5mm1j5k4692vlpd.apps.googleusercontent.com',
    iosClientId:
        '639171720797-1947q85ikvusptoul5tdhjffodrlhlrh.apps.googleusercontent.com',
    iosBundleId: 'com.reformeddeveloper.adhdJournal.test1',
  );
}
